import { Country, Language, Product } from './types';
export const COUNTRIES: Country[] = [
  { name: 'India', code: 'IN', currency: { code: 'INR', symbol: '₹', rate: 1 }, active: true, language: 'English (US)' },
  { name: 'United States', code: 'US', currency: { code: 'USD', symbol: '$', rate: 0.012 }, active: true, language: 'English (US)' },
  { name: 'United Kingdom', code: 'GB', currency: { code: 'GBP', symbol: '£', rate: 0.0095 }, active: true, language: 'English (US)' },
  { name: 'United Arab Emirates', code: 'AE', currency: { code: 'AED', symbol: 'د.إ', rate: 0.044 }, active: true, language: 'Arabic' },
  { name: 'France', code: 'FR', currency: { code: 'EUR', symbol: '€', rate: 0.011 }, active: true, language: 'French' },
];
export const LANGUAGES: Language[] = ['English (US)', 'French', 'Arabic'];

export const COLLECTIONS = [
  {
    id: 'three-piece-suit',
    fullName: '3 Piece Suit',
    shortName: '3 Piece Suit',
    descriptor: 'Complete tailored ensembles for the discerning gentleman.',
    image: '/placeholder.svg',
    narrative: 'The ultimate expression of tailored perfection.',
    craftsmanship: 'Three-layer canvas construction for a flawless drape.',
    packaging: 'Archival garment carrier with custom hangers.',
  },
  {
    id: 'tuxedo',
    fullName: 'Tuxedo',
    shortName: 'Tuxedo',
    descriptor: 'The pinnacle of formal evening wear.',
    image: '/placeholder.svg',
    narrative: 'Crafted for the most prestigious occasions.',
    craftsmanship: 'Traditional canvassing and satin peak lapels.',
    packaging: 'Structured carrier with archival hangers.',
  },
  {
    id: 'jodhpuri',
    fullName: 'Jodhpuri',
    shortName: 'Jodhpuri',
    descriptor: 'Regal Jodhpuri jackets for a commanding presence.',
    image: '/placeholder.svg',
    narrative: 'A symbol of heritage and authority.',
    craftsmanship: 'Structured shoulders and hand-carved buttons.',
    packaging: 'Signature archival box with certificate.',
  },
  {
    id: 'koti-pant',
    fullName: 'Koti Pant',
    shortName: 'Koti Pant',
    descriptor: 'Indo-western fusion featuring tailored kotis and trousers.',
    image: '/placeholder.svg',
    narrative: 'For the modern trendsetter.',
    craftsmanship: 'Sharp silhouettes in premium wool-silk blends.',
    packaging: 'Signature archival box.',
  },
  {
    id: 'koti-kurta',
    fullName: 'Koti Kurta',
    shortName: 'Koti Kurta',
    descriptor: 'Traditional silhouettes with a modern koti layer.',
    image: '/placeholder.svg',
    narrative: 'A refined fusion of tradition and tailoring.',
    craftsmanship: 'Hand-finished kotis with intricate detailing.',
    packaging: 'Custom silk dust-bag wrap.',
  },
  {
    id: 'kurta',
    fullName: 'Kurta',
    shortName: 'Kurta',
    descriptor: 'Timeless kurtas crafted from the finest silks and linens.',
    image: '/placeholder.svg',
    narrative: 'The soul of LUXARDO FASHION.',
    craftsmanship: 'Precision cut and hand-finished seams.',
    packaging: 'Acid-free tissue wrapping in archival box.',
  },
  {
    id: 'casual',
    fullName: 'Casual',
    shortName: 'Casual',
    descriptor: 'Modern tailored shirts and trousers for daily luxury.',
    image: '/placeholder.svg',
    narrative: 'Contemporary workwear, refined.',
    craftsmanship: 'Precision stitching and premium cotton blends.',
    packaging: 'Signature LUXARDO FASHION box.',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: '3ps-flagship-01',
    name: 'Sovrano Three-Piece Suit',
    slug: 'sovrano-three-piece-suit',
    category: '3 Piece Suit',
    collection: 'three-piece-suit',
    price: 89999,
    image: '/placeholder.svg',
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
    ],
    description: 'A flagship three-piece ensemble in midnight wool with full canvas construction, peak lapels and a matching waistcoat. Cut for a structured modern silhouette.',
    fabricOrigin: 'Italy',
    composition: '95% Super 120s Wool, 5% Mulberry Silk',
    washingCare: 'Dry clean only • Do not bleach • Iron at low temp (≤110°C) • Steam to refresh',
    shipping: 'Complimentary worldwide shipping on orders above ₹25,000. 3–7 business days dispatch.',
    returns: '14-day return window on unworn, tagged items in original packaging.',
    garmentFormat: 'Delivered ready-to-stitch as a premium fabric set in our archival presentation box. Tailoring not included.',
    readyToStitch: true,
    readyToStitchInfo: 'Includes coat, waistcoat & trouser fabric panels, signature lining, and a tailoring guide.',
    stock: 12,
    lowStockThreshold: 3,
    visibility: 'public',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tux-flagship-01',
    name: 'Notturno Satin-Lapel Tuxedo',
    slug: 'notturno-satin-lapel-tuxedo',
    category: 'Tuxedo',
    collection: 'tuxedo',
    price: 79999,
    image: '/placeholder.svg',
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
    ],
    description: 'An evening tuxedo in jet black with satin peak lapels, covered buttons, and a single besom welt pocket. The definitive black-tie cut.',
    fabricOrigin: 'Italy',
    composition: '100% Super 130s Worsted Wool with Silk Satin facing',
    washingCare: 'Dry clean only • Iron at low temp • Cover lapels before pressing',
    shipping: 'Complimentary worldwide shipping. 3–7 business days dispatch.',
    returns: '14-day return window on unworn, tagged items.',
    garmentFormat: 'Ready-to-stitch fabric set in archival presentation box. Tailoring not included.',
    readyToStitch: true,
    stock: 9,
    visibility: 'public',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jod-flagship-01',
    name: 'Maharaja Jodhpuri Bandhgala',
    slug: 'maharaja-jodhpuri-bandhgala',
    category: 'Jodhpuri',
    collection: 'jodhpuri',
    price: 64999,
    image: '/placeholder.svg',
    images: [
      '/placeholder.svg',
    ],
    description: 'Structured Jodhpuri bandhgala with mandarin collar, hand-carved horn buttons and an embroidered chest motif. Worn with tapered trousers.',
    fabricOrigin: 'India',
    composition: '70% Wool, 25% Silk, 5% Polyester (lining)',
    washingCare: 'Dry clean only',
    shipping: 'Complimentary worldwide shipping. 3–7 business days dispatch.',
    returns: '14-day return window on unworn, tagged items.',
    garmentFormat: 'Ready-to-stitch fabric set in archival box. Tailoring not included.',
    readyToStitch: true,
    stock: 15,
    visibility: 'public',
    featured: true,
    createdAt: new Date().toISOString(),
  }
];
