import { Country } from './types';

const countryData = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Côte d'Ivoire", code: "CI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czechia", code: "CZ" },
  { name: "Democratic Republic of the Congo", code: "CD" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Holy See", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine State", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" }
];

export const ALL_COUNTRIES: Country[] = countryData.map(data => ({
  name: data.name,
  code: data.code,
  language: 'English (US)',
  currency: { code: 'INR', symbol: '₹', rate: 1 }, // Defaulting to INR for simplicity
  active: true
}));

const specificData: Record<string, Partial<Country>> = {
  "Afghanistan": { code: 'AF', currency: { code: 'AFN', symbol: 'AFN', rate: 0.692212 } },
  "Albania": { code: 'AL', currency: { code: 'ALL', symbol: 'ALL', rate: 0.876453 } },
  "Algeria": { code: 'DZ', currency: { code: 'DZD', symbol: 'DZD', rate: 1.416791 } },
  "Andorra": { code: 'AD', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Angola": { code: 'AO', currency: { code: 'AOA', symbol: 'AOA', rate: 10.048651 } },
  "Antigua and Barbuda": { code: 'AG', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Argentina": { code: 'AR', currency: { code: 'ARS', symbol: 'ARS', rate: 14.597922 } },
  "Armenia": { code: 'AM', currency: { code: 'AMD', symbol: 'AMD', rate: 4.023537 } },
  "Australia": { code: 'AU', currency: { code: 'AUD', symbol: 'A$', rate: 0.015139 } },
  "Austria": { code: 'AT', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Azerbaijan": { code: 'AZ', currency: { code: 'AZN', symbol: 'AZN', rate: 0.018207 } },
  "Bahamas": { code: 'BS', currency: { code: 'BSD', symbol: 'BSD', rate: 0.010712 } },
  "Bahrain": { code: 'BH', currency: { code: 'BHD', symbol: 'BHD', rate: 0.004028 } },
  "Bangladesh": { code: 'BD', currency: { code: 'BDT', symbol: 'BDT', rate: 1.31803 } },
  "Barbados": { code: 'BB', currency: { code: 'BBD', symbol: 'BBD', rate: 0.021423 } },
  "Belarus": { code: 'BY', currency: { code: 'BYN', symbol: 'BYN', rate: 0.030554 } },
  "Belgium": { code: 'BE', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Belize": { code: 'BZ', currency: { code: 'BZD', symbol: 'BZD', rate: 0.021423 } },
  "Benin": { code: 'BJ', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Bhutan": { code: 'BT', currency: { code: 'BTN', symbol: 'BTN', rate: 1 } },
  "Bolivia": { code: 'BO', currency: { code: 'BOB', symbol: 'BOB', rate: 0.074197 } },
  "Bosnia and Herzegovina": { code: 'BA', currency: { code: 'BAM', symbol: 'BAM', rate: 0.01789 } },
  "Botswana": { code: 'BW', currency: { code: 'BWP', symbol: 'BWP', rate: 0.14776 } },
  "Brazil": { code: 'BR', currency: { code: 'BRL', symbol: 'R$', rate: 0.05375 } },
  "Brunei": { code: 'BN', currency: { code: 'BND', symbol: 'BND', rate: 0.013664 } },
  "Bulgaria": { code: 'BG', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Burkina Faso": { code: 'BF', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Burundi": { code: 'BI', currency: { code: 'BIF', symbol: 'BIF', rate: 31.864078 } },
  "Côte d'Ivoire": { code: 'CI', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Cabo Verde": { code: 'CV', currency: { code: 'CVE', symbol: 'CVE', rate: 1.008616 } },
  "Cambodia": { code: 'KH', currency: { code: 'KHR', symbol: 'KHR', rate: 42.623377 } },
  "Cameroon": { code: 'CM', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Canada": { code: 'CA', currency: { code: 'CAD', symbol: 'CA$', rate: 0.014815 } },
  "Central African Republic": { code: 'CF', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Chad": { code: 'TD', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Chile": { code: 'CL', currency: { code: 'CLP', symbol: 'CLP', rate: 9.613491 } },
  "China": { code: 'CN', currency: { code: 'CNY', symbol: 'CN¥', rate: 0.073477 } },
  "Colombia": { code: 'CO', currency: { code: 'COP', symbol: 'COP', rate: 39.03607 } },
  "Comoros": { code: 'KM', currency: { code: 'KMF', symbol: 'KMF', rate: 4.500127 } },
  "Congo": { code: 'CG', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Costa Rica": { code: 'CR', currency: { code: 'CRC', symbol: 'CRC', rate: 4.962826 } },
  "Croatia": { code: 'HR', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Cuba": { code: 'CU', currency: { code: 'CUP', symbol: 'CUP', rate: 0.257078 } },
  "Cyprus": { code: 'CY', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Czechia": { code: 'CZ', currency: { code: 'CZK', symbol: 'CZK', rate: 0.223212 } },
  "Democratic Republic of the Congo": { code: 'CD', currency: { code: 'CDF', symbol: 'CDF', rate: 24.863636 } },
  "Denmark": { code: 'DK', currency: { code: 'DKK', symbol: 'DKK', rate: 0.068242 } },
  "Djibouti": { code: 'DJ', currency: { code: 'DJF', symbol: 'DJF', rate: 1.903677 } },
  "Dominica": { code: 'DM', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Dominican Republic": { code: 'DO', currency: { code: 'DOP', symbol: 'DOP', rate: 0.643871 } },
  "Ecuador": { code: 'EC', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Egypt": { code: 'EG', currency: { code: 'EGP', symbol: 'EGP', rate: 0.569577 } },
  "El Salvador": { code: 'SV', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Equatorial Guinea": { code: 'GQ', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Eritrea": { code: 'ER', currency: { code: 'ERN', symbol: 'ERN', rate: 0.160674 } },
  "Estonia": { code: 'EE', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Eswatini": { code: 'SZ', currency: { code: 'SZL', symbol: 'SZL', rate: 0.176796 } },
  "Ethiopia": { code: 'ET', currency: { code: 'ETB', symbol: 'ETB', rate: 1.679632 } },
  "Fiji": { code: 'FJ', currency: { code: 'FJD', symbol: 'FJD', rate: 0.02367 } },
  "Finland": { code: 'FI', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "France": { code: 'FR', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Gabon": { code: 'GA', currency: { code: 'XAF', symbol: 'FCFA', rate: 6.000169 } },
  "Gambia": { code: 'GM', currency: { code: 'GMD', symbol: 'GMD', rate: 0.794369 } },
  "Georgia": { code: 'GE', currency: { code: 'GEL', symbol: 'GEL', rate: 0.028914 } },
  "Germany": { code: 'DE', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Ghana": { code: 'GH', currency: { code: 'GHS', symbol: 'GHS', rate: 0.118769 } },
  "Greece": { code: 'GR', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Grenada": { code: 'GD', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Guatemala": { code: 'GT', currency: { code: 'GTQ', symbol: 'GTQ', rate: 0.081929 } },
  "Guinea": { code: 'GN', currency: { code: 'GNF', symbol: 'GNF', rate: 93.876593 } },
  "Guinea-Bissau": { code: 'GW', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Guyana": { code: 'GY', currency: { code: 'GYD', symbol: 'GYD', rate: 2.240273 } },
  "Haiti": { code: 'HT', currency: { code: 'HTG', symbol: 'HTG', rate: 1.401965 } },
  "Holy See": { code: 'VA', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Honduras": { code: 'HN', currency: { code: 'HNL', symbol: 'HNL', rate: 0.284578 } },
  "Hungary": { code: 'HU', currency: { code: 'HUF', symbol: 'HUF', rate: 3.33778 } },
  "Iceland": { code: 'IS', currency: { code: 'ISK', symbol: 'ISK', rate: 1.312248 } },
  "India": { code: 'IN', currency: { code: 'INR', symbol: '₹', rate: 1 } },
  "Indonesia": { code: 'ID', currency: { code: 'IDR', symbol: 'IDR', rate: 183.006584 } },
  "Iran": { code: 'IR', currency: { code: 'IRR', symbol: 'IRR', rate: 890.521126 } },
  "Iraq": { code: 'IQ', currency: { code: 'IQD', symbol: 'IQD', rate: 14.025641 } },
  "Ireland": { code: 'IE', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Israel": { code: 'IL', currency: { code: 'ILS', symbol: '₪', rate: 0.032651 } },
  "Italy": { code: 'IT', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Jamaica": { code: 'JM', currency: { code: 'JMD', symbol: 'JMD', rate: 1.692628 } },
  "Japan": { code: 'JP', currency: { code: 'JPY', symbol: '¥', rate: 1.709977 } },
  "Jordan": { code: 'JO', currency: { code: 'JOD', symbol: 'JOD', rate: 0.007595 } },
  "Kazakhstan": { code: 'KZ', currency: { code: 'KZT', symbol: 'KZT', rate: 5.090666 } },
  "Kenya": { code: 'KE', currency: { code: 'KES', symbol: 'KES', rate: 1.386542 } },
  "Kiribati": { code: 'KI', currency: { code: 'AUD', symbol: 'A$', rate: 0.015139 } },
  "Kuwait": { code: 'KW', currency: { code: 'KWD', symbol: 'KWD', rate: 0.003296 } },
  "Kyrgyzstan": { code: 'KG', currency: { code: 'KGS', symbol: 'KGS', rate: 0.93688 } },
  "Laos": { code: 'LA', currency: { code: 'LAK', symbol: 'LAK', rate: 235.509556 } },
  "Latvia": { code: 'LV', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Lebanon": { code: 'LB', currency: { code: 'LBP', symbol: 'LBP', rate: 958.688534 } },
  "Lesotho": { code: 'LS', currency: { code: 'LSL', symbol: 'LSL', rate: 0.176796 } },
  "Liberia": { code: 'LR', currency: { code: 'LRD', symbol: 'LRD', rate: 1.972456 } },
  "Libya": { code: 'LY', currency: { code: 'LYD', symbol: 'LYD', rate: 0.068057 } },
  "Liechtenstein": { code: 'LI', currency: { code: 'CHF', symbol: 'CHF', rate: 0.008454 } },
  "Lithuania": { code: 'LT', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Luxembourg": { code: 'LU', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Madagascar": { code: 'MG', currency: { code: 'MGA', symbol: 'MGA', rate: 44.351351 } },
  "Malawi": { code: 'MW', currency: { code: 'MWK', symbol: 'MWK', rate: 18.658225 } },
  "Malaysia": { code: 'MY', currency: { code: 'MYR', symbol: 'MYR', rate: 0.042606 } },
  "Maldives": { code: 'MV', currency: { code: 'MVR', symbol: 'MVR', rate: 0.16556 } },
  "Mali": { code: 'ML', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Malta": { code: 'MT', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Marshall Islands": { code: 'MH', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Mauritania": { code: 'MR', currency: { code: 'MRU', symbol: 'MRU', rate: 0.42846 } },
  "Mauritius": { code: 'MU', currency: { code: 'MUR', symbol: 'MUR', rate: 0.50338 } },
  "Mexico": { code: 'MX', currency: { code: 'MXN', symbol: 'MX$', rate: 0.18604 } },
  "Micronesia": { code: 'FM', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Moldova": { code: 'MD', currency: { code: 'MDL', symbol: 'MDL', rate: 0.184025 } },
  "Monaco": { code: 'MC', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Mongolia": { code: 'MN', currency: { code: 'MNT', symbol: 'MNT', rate: 38.643618 } },
  "Montenegro": { code: 'ME', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Morocco": { code: 'MA', currency: { code: 'MAD', symbol: 'MAD', rate: 0.099437 } },
  "Mozambique": { code: 'MZ', currency: { code: 'MZN', symbol: 'MZN', rate: 0.682939 } },
  "Myanmar": { code: 'MM', currency: { code: 'MMK', symbol: 'MMK', rate: 22.486582 } },
  "Namibia": { code: 'NA', currency: { code: 'NAD', symbol: 'NAD', rate: 0.176796 } },
  "Nauru": { code: 'NR', currency: { code: 'AUD', symbol: 'A$', rate: 0.015139 } },
  "Nepal": { code: 'NP', currency: { code: 'NPR', symbol: 'NPR', rate: 1.6 } },
  "Netherlands": { code: 'NL', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "New Zealand": { code: 'NZ', currency: { code: 'NZD', symbol: 'NZ$', rate: 0.018307 } },
  "Nicaragua": { code: 'NI', currency: { code: 'NIO', symbol: 'NIO', rate: 0.394025 } },
  "Niger": { code: 'NE', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Nigeria": { code: 'NG', currency: { code: 'NGN', symbol: 'NGN', rate: 14.55482 } },
  "North Korea": { code: 'KP', currency: { code: 'KPW', symbol: 'KPW', rate: 1 } },
  "North Macedonia": { code: 'MK', currency: { code: 'MKD', symbol: 'MKD', rate: 0.568843 } },
  "Norway": { code: 'NO', currency: { code: 'NOK', symbol: 'NOK', rate: 0.101595 } },
  "Oman": { code: 'OM', currency: { code: 'OMR', symbol: 'OMR', rate: 0.004119 } },
  "Pakistan": { code: 'PK', currency: { code: 'PKR', symbol: 'PKR', rate: 2.993284 } },
  "Palau": { code: 'PW', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Palestine State": { code: 'PS', currency: { code: 'ILS', symbol: '₪', rate: 0.032651 } },
  "Panama": { code: 'PA', currency: { code: 'PAB', symbol: 'PAB', rate: 0.010712 } },
  "Papua New Guinea": { code: 'PG', currency: { code: 'PGK', symbol: 'PGK', rate: 0.046644 } },
  "Paraguay": { code: 'PY', currency: { code: 'PYG', symbol: 'PYG', rate: 68.982386 } },
  "Peru": { code: 'PE', currency: { code: 'PEN', symbol: 'PEN', rate: 0.036197 } },
  "Philippines": { code: 'PH', currency: { code: 'PHP', symbol: '₱', rate: 0.643706 } },
  "Poland": { code: 'PL', currency: { code: 'PLN', symbol: 'PLN', rate: 0.038926 } },
  "Portugal": { code: 'PT', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Qatar": { code: 'QA', currency: { code: 'QAR', symbol: 'QAR', rate: 0.03899 } },
  "Romania": { code: 'RO', currency: { code: 'RON', symbol: 'RON', rate: 0.046665 } },
  "Russia": { code: 'RU', currency: { code: 'RUB', symbol: 'RUB', rate: 0.816208 } },
  "Rwanda": { code: 'RW', currency: { code: 'RWF', symbol: 'RWF', rate: 15.605225 } },
  "Saint Kitts and Nevis": { code: 'KN', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Saint Lucia": { code: 'LC', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Saint Vincent and the Grenadines": { code: 'VC', currency: { code: 'XCD', symbol: 'EC$', rate: 0.028921 } },
  "Samoa": { code: 'WS', currency: { code: 'WST', symbol: 'WST', rate: 0.029114 } },
  "San Marino": { code: 'SM', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Sao Tome and Principe": { code: 'ST', currency: { code: 'STN', symbol: 'STN', rate: 0.224106 } },
  "Saudi Arabia": { code: 'SA', currency: { code: 'SAR', symbol: 'SAR', rate: 0.040169 } },
  "Senegal": { code: 'SN', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Serbia": { code: 'RS', currency: { code: 'RSD', symbol: 'RSD', rate: 1.073606 } },
  "Seychelles": { code: 'SC', currency: { code: 'SCR', symbol: 'SCR', rate: 0.15831 } },
  "Sierra Leone": { code: 'SL', currency: { code: 'SLE', symbol: 'SLE', rate: 0.264736 } },
  "Singapore": { code: 'SG', currency: { code: 'SGD', symbol: 'SGD', rate: 0.013664 } },
  "Slovakia": { code: 'SK', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Slovenia": { code: 'SI', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Solomon Islands": { code: 'SB', currency: { code: 'SBD', symbol: 'SBD', rate: 0.085997 } },
  "Somalia": { code: 'SO', currency: { code: 'SOS', symbol: 'SOS', rate: 6.123134 } },
  "South Africa": { code: 'ZA', currency: { code: 'ZAR', symbol: 'ZAR', rate: 0.176959 } },
  "South Korea": { code: 'KR', currency: { code: 'KRW', symbol: '₩', rate: 15.88182 } },
  "South Sudan": { code: 'SS', currency: { code: 'SSP', symbol: 'SSP', rate: 49.293763 } },
  "Spain": { code: 'ES', currency: { code: 'EUR', symbol: '€', rate: 0.009147 } },
  "Sri Lanka": { code: 'LK', currency: { code: 'LKR', symbol: 'LKR', rate: 3.380625 } },
  "Sudan": { code: 'SD', currency: { code: 'SDG', symbol: 'SDG', rate: 4.784257 } },
  "Suriname": { code: 'SR', currency: { code: 'SRD', symbol: 'SRD', rate: 0.402798 } },
  "Sweden": { code: 'SE', currency: { code: 'SEK', symbol: 'SEK', rate: 0.099461 } },
  "Switzerland": { code: 'CH', currency: { code: 'CHF', symbol: 'CHF', rate: 0.008454 } },
  "Syria": { code: 'SY', currency: { code: 'SYP', symbol: 'SYP', rate: 1.202698 } },
  "Tajikistan": { code: 'TJ', currency: { code: 'TJS', symbol: 'TJS', rate: 0.102828 } },
  "Tanzania": { code: 'TZ', currency: { code: 'TZS', symbol: 'TZS', rate: 27.917765 } },
  "Thailand": { code: 'TH', currency: { code: 'THB', symbol: 'THB', rate: 0.344695 } },
  "Timor-Leste": { code: 'TL', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Togo": { code: 'TG', currency: { code: 'XOF', symbol: 'F CFA', rate: 6.000169 } },
  "Tonga": { code: 'TO', currency: { code: 'TOP', symbol: 'TOP', rate: 0.025533 } },
  "Trinidad and Tobago": { code: 'TT', currency: { code: 'TTD', symbol: 'TTD', rate: 0.07261 } },
  "Tunisia": { code: 'TN', currency: { code: 'TND', symbol: 'TND', rate: 0.03107 } },
  "Turkey": { code: 'TR', currency: { code: 'TRY', symbol: 'TRY', rate: 0.479204 } },
  "Turkmenistan": { code: 'TM', currency: { code: 'TMT', symbol: 'TMT', rate: 0.037805 } },
  "Tuvalu": { code: 'TV', currency: { code: 'AUD', symbol: 'A$', rate: 0.015139 } },
  "Uganda": { code: 'UG', currency: { code: 'UGX', symbol: 'UGX', rate: 39.821013 } },
  "Ukraine": { code: 'UA', currency: { code: 'UAH', symbol: 'UAH', rate: 0.465602 } },
  "United Arab Emirates": { code: 'AE', currency: { code: 'AED', symbol: 'AED', rate: 0.039338 } },
  "United Kingdom": { code: 'GB', currency: { code: 'GBP', symbol: '£', rate: 0.007963 } },
  "United States": { code: 'US', currency: { code: 'USD', symbol: '$', rate: 0.010712 } },
  "Uruguay": { code: 'UY', currency: { code: 'UYU', symbol: 'UYU', rate: 0.432604 } },
  "Uzbekistan": { code: 'UZ', currency: { code: 'UZS', symbol: 'UZS', rate: 131.295709 } },
  "Vanuatu": { code: 'VU', currency: { code: 'VUV', symbol: 'VUV', rate: 1.276865 } },
  "Venezuela": { code: 'VE', currency: { code: 'VED', symbol: 'VED', rate: 1 } },
  "Vietnam": { code: 'VN', currency: { code: 'VND', symbol: '₫', rate: 280.7172 } },
  "Yemen": { code: 'YE', currency: { code: 'YER', symbol: 'YER', rate: 2.550681 } },
  "Zambia": { code: 'ZM', currency: { code: 'ZMW', symbol: 'ZMW', rate: 0.204702 } },
  "Zimbabwe": { code: 'ZW', currency: { code: 'ZWG', symbol: 'ZWG', rate: 0.270267 } },
};

ALL_COUNTRIES.forEach(country => {
  if (specificData[country.name]) {
    Object.assign(country, specificData[country.name]);
  }
});
